server:
  port: 5001
  error:
    whitelabel:
      enabled: true

app:
  passwordKey: sorkaksemsvmfpdla

jasypt:
  encryptor:
    bean: encryptorBean

## local
spring:
  datasource:
    url: ENC(P+jF6zXb1WaB0RMeCEyYu8IMaWpudtJEF/FoK/Yyta22wnVpEBWl3/8b+P0aemJdU+rzE1ICMbmZw6iLis7ETfn1U/2llgOuD1IEO3oHXQ0=)
    username: ENC(8uziWrf3YlQ3l0Oljwm6dg==)
    password: ENC(Kxq4ZMWnt9+Y/7zPh6VKYQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor:
      sql: trace
