server:
  port: 5001
  error:
    whitelabel:
      enabled: true

app:
  passwordKey: sorkaksemsvmfpdla

jasypt:
  encryptor:
    bean: encryptorBean

## local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/query_study?serverTimezone=Asia/Seoul
    username: ENC(8uziWrf3YlQ3l0Oljwm6dg==)
    password: ENC(Kxq4ZMWnt9+Y/7zPh6VKYQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  profiles:
    active: local
  main:
    lazy-initialization: true
  devtools:
    livereload:
      enabled: true
      restart:
        additional-paths: META-INF/**
        enabled: true
